export const states = {
    STANDING_RIGHT: 0,
    STANDING_LEFT: 1,
    WALKING_RIGHT: 2,
    WALKING_LEFT: 3,
    DASH_RIGHT: 4,
    DASH_LEFT: 5,
    JUMPING_RIGHT: 6,
    JUMPING_LEFT: 7,
    FALLING_RIGHT: 8,
    FALLING_LEFT: 9
}

export const keys = {
    PRESS_RIGHT: 'PRESS RIGHT',
    PRESS_LEFT: 'PRESS LEFT',
    PRESS_DOWN: 'PRESS DOWN',
    PRESS_UP: 'PRESS UP',
    PRESS_BUTTON_A: 'PRESS BUTTON A',
    PRESS_BUTTON_B: 'PRESS BUTTON B',
    PRESS_BUTTON_C: 'PRESS BUTTON C',
    PRESS_BUTTON_D: 'PRESS BUTTON D',
    PRESS_BUTTON_E: 'PRESS BUTTON E',
    RELEASE_RIGHT: 'RELEASE RIGHT',
    RELEASE_LEFT: 'RELEASE LEFT',
    RELEASE_DOWN: 'RELEASE DOWN',
    RELEASE_UP: 'RELEASE UP',
    RELEASE_BUTTON_A: 'RELEASE BUTTON A',
    RELEASE_BUTTON_B: 'RELEASE BUTTON B',
    RELEASE_BUTTON_C: 'RELEASE BUTTON C',
    RELEASE_BUTTON_D: 'RELEASE BUTTON D',
    RELEASE_BUTTON_E: 'RELEASE BUTTON E'      
}
export const controls = {
    LEFT: 'a',
    RIGHT: 'd',
    DOWN: 's',
    UP: 'w',
    LIGHT_ATTACK: 'ArrowLeft',
    MEDIUM_ATTACK: 'ArrowDown',
    DASH: 'ArrowRight',
    SIGNATURE: 'ArrowUp',
    GRAPPLE: 'h'
}